all: sequential_implementation student_submission

sequential_implementation:
	g++.exe -Wall -o sequential_implementation -O3 sequential_implementation.cpp

student_submission:
	g++.exe -Wall -o student_submission -O3 student_submission.cpp
